//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orion {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Convenio : global::System.Configuration.ApplicationSettingsBase {
        
        private static Convenio defaultInstance = ((Convenio)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Convenio())));
        
        public static Convenio Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("07:20:00")]
        public global::System.TimeSpan JornadaMedia {
            get {
                return ((global::System.TimeSpan)(this["JornadaMedia"]));
            }
            set {
                this["JornadaMedia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14.49")]
        public decimal ImporteDietas {
            get {
                return ((decimal)(this["ImporteDietas"]));
            }
            set {
                this["ImporteDietas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22:00:00")]
        public global::System.TimeSpan InicioNocturnas {
            get {
                return ((global::System.TimeSpan)(this["InicioNocturnas"]));
            }
            set {
                this["InicioNocturnas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("06:00:00")]
        public global::System.TimeSpan FinalNocturnas {
            get {
                return ((global::System.TimeSpan)(this["FinalNocturnas"]));
            }
            set {
                this["FinalNocturnas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("06:00:00")]
        public global::System.TimeSpan HoraDesayuno {
            get {
                return ((global::System.TimeSpan)(this["HoraDesayuno"]));
            }
            set {
                this["HoraDesayuno"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int PorcentajeDesayuno {
            get {
                return ((int)(this["PorcentajeDesayuno"]));
            }
            set {
                this["PorcentajeDesayuno"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12:30:00")]
        public global::System.TimeSpan InicioComidaContinuo {
            get {
                return ((global::System.TimeSpan)(this["InicioComidaContinuo"]));
            }
            set {
                this["InicioComidaContinuo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15:30:00")]
        public global::System.TimeSpan FinalComidaContinuo {
            get {
                return ((global::System.TimeSpan)(this["FinalComidaContinuo"]));
            }
            set {
                this["FinalComidaContinuo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11:45:00")]
        public global::System.TimeSpan InicioComidaPartido {
            get {
                return ((global::System.TimeSpan)(this["InicioComidaPartido"]));
            }
            set {
                this["InicioComidaPartido"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15:15:00")]
        public global::System.TimeSpan FinalComidaPartido {
            get {
                return ((global::System.TimeSpan)(this["FinalComidaPartido"]));
            }
            set {
                this["FinalComidaPartido"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22:00:00")]
        public global::System.TimeSpan InicioCena {
            get {
                return ((global::System.TimeSpan)(this["InicioCena"]));
            }
            set {
                this["InicioCena"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23:00:00")]
        public global::System.TimeSpan FinalCena {
            get {
                return ((global::System.TimeSpan)(this["FinalCena"]));
            }
            set {
                this["FinalCena"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan InicioPlusCena {
            get {
                return ((global::System.TimeSpan)(this["InicioPlusCena"]));
            }
            set {
                this["InicioPlusCena"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int PorcentajePlusCena {
            get {
                return ((int)(this["PorcentajePlusCena"]));
            }
            set {
                this["PorcentajePlusCena"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int MaxHorasCobradas {
            get {
                return ((int)(this["MaxHorasCobradas"]));
            }
            set {
                this["MaxHorasCobradas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("225")]
        public int TrabajoAnuales {
            get {
                return ((int)(this["TrabajoAnuales"]));
            }
            set {
                this["TrabajoAnuales"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("109")]
        public int DescansosAnuales {
            get {
                return ((int)(this["DescansosAnuales"]));
            }
            set {
                this["DescansosAnuales"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("31")]
        public int VacacionesAnuales {
            get {
                return ((int)(this["VacacionesAnuales"]));
            }
            set {
                this["VacacionesAnuales"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("41.12")]
        public decimal ImporteFestivos {
            get {
                return ((decimal)(this["ImporteFestivos"]));
            }
            set {
                this["ImporteFestivos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5.14")]
        public decimal ImporteSabados {
            get {
                return ((decimal)(this["ImporteSabados"]));
            }
            set {
                this["ImporteSabados"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8.69")]
        public decimal DietaMenorDescanso {
            get {
                return ((decimal)(this["DietaMenorDescanso"]));
            }
            set {
                this["DietaMenorDescanso"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9.83")]
        public decimal PlusLimpieza {
            get {
                return ((decimal)(this["PlusLimpieza"]));
            }
            set {
                this["PlusLimpieza"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7.63")]
        public decimal PlusPaqueteria {
            get {
                return ((decimal)(this["PlusPaqueteria"]));
            }
            set {
                this["PlusPaqueteria"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("08:30:00")]
        public global::System.TimeSpan MaxHorasLaborables {
            get {
                return ((global::System.TimeSpan)(this["MaxHorasLaborables"]));
            }
            set {
                this["MaxHorasLaborables"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("09:00:00")]
        public global::System.TimeSpan MaxHorasFinesSemana {
            get {
                return ((global::System.TimeSpan)(this["MaxHorasFinesSemana"]));
            }
            set {
                this["MaxHorasFinesSemana"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public decimal PlusNocturnidad {
            get {
                return ((decimal)(this["PlusNocturnidad"]));
            }
            set {
                this["PlusNocturnidad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public decimal PlusNavidad {
            get {
                return ((decimal)(this["PlusNavidad"]));
            }
            set {
                this["PlusNavidad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10:00:00")]
        public global::System.TimeSpan MaxHorasTotalGraficoPartido {
            get {
                return ((global::System.TimeSpan)(this["MaxHorasTotalGraficoPartido"]));
            }
            set {
                this["MaxHorasTotalGraficoPartido"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("03:00:00")]
        public global::System.TimeSpan MaxHorasParticionGraficoPartido {
            get {
                return ((global::System.TimeSpan)(this["MaxHorasParticionGraficoPartido"]));
            }
            set {
                this["MaxHorasParticionGraficoPartido"] = value;
            }
        }
    }
}
