//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orion {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class PorCentro : global::System.Configuration.ApplicationSettingsBase {
        
        private static PorCentro defaultInstance = ((PorCentro)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PorCentro())));
        
        public static PorCentro Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LunDelArrasate {
            get {
                return ((int)(this["LunDelArrasate"]));
            }
            set {
                this["LunDelArrasate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LunAlArrasate {
            get {
                return ((int)(this["LunAlArrasate"]));
            }
            set {
                this["LunAlArrasate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VieDelArrasate {
            get {
                return ((int)(this["VieDelArrasate"]));
            }
            set {
                this["VieDelArrasate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VieAlArrasate {
            get {
                return ((int)(this["VieAlArrasate"]));
            }
            set {
                this["VieAlArrasate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SabDelArrasate {
            get {
                return ((int)(this["SabDelArrasate"]));
            }
            set {
                this["SabDelArrasate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SabAlArrasate {
            get {
                return ((int)(this["SabAlArrasate"]));
            }
            set {
                this["SabAlArrasate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DomDelArrasate {
            get {
                return ((int)(this["DomDelArrasate"]));
            }
            set {
                this["DomDelArrasate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DomAlArrasate {
            get {
                return ((int)(this["DomAlArrasate"]));
            }
            set {
                this["DomAlArrasate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LunDelBilbao {
            get {
                return ((int)(this["LunDelBilbao"]));
            }
            set {
                this["LunDelBilbao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LunAlBilbao {
            get {
                return ((int)(this["LunAlBilbao"]));
            }
            set {
                this["LunAlBilbao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VieDelBilbao {
            get {
                return ((int)(this["VieDelBilbao"]));
            }
            set {
                this["VieDelBilbao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VieAlBilbao {
            get {
                return ((int)(this["VieAlBilbao"]));
            }
            set {
                this["VieAlBilbao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SabDelBilbao {
            get {
                return ((int)(this["SabDelBilbao"]));
            }
            set {
                this["SabDelBilbao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SabAlBilbao {
            get {
                return ((int)(this["SabAlBilbao"]));
            }
            set {
                this["SabAlBilbao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DomDelBilbao {
            get {
                return ((int)(this["DomDelBilbao"]));
            }
            set {
                this["DomDelBilbao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DomAlBilbao {
            get {
                return ((int)(this["DomAlBilbao"]));
            }
            set {
                this["DomAlBilbao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LunDelDonosti {
            get {
                return ((int)(this["LunDelDonosti"]));
            }
            set {
                this["LunDelDonosti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LunAlDonosti {
            get {
                return ((int)(this["LunAlDonosti"]));
            }
            set {
                this["LunAlDonosti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VieDelDonosti {
            get {
                return ((int)(this["VieDelDonosti"]));
            }
            set {
                this["VieDelDonosti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VieAlDonosti {
            get {
                return ((int)(this["VieAlDonosti"]));
            }
            set {
                this["VieAlDonosti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SabDelDonosti {
            get {
                return ((int)(this["SabDelDonosti"]));
            }
            set {
                this["SabDelDonosti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SabAlDonosti {
            get {
                return ((int)(this["SabAlDonosti"]));
            }
            set {
                this["SabAlDonosti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DomDelDonosti {
            get {
                return ((int)(this["DomDelDonosti"]));
            }
            set {
                this["DomDelDonosti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DomAlDonosti {
            get {
                return ((int)(this["DomAlDonosti"]));
            }
            set {
                this["DomAlDonosti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LunDelVitoria {
            get {
                return ((int)(this["LunDelVitoria"]));
            }
            set {
                this["LunDelVitoria"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LunAlVitoria {
            get {
                return ((int)(this["LunAlVitoria"]));
            }
            set {
                this["LunAlVitoria"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VieDelVitoria {
            get {
                return ((int)(this["VieDelVitoria"]));
            }
            set {
                this["VieDelVitoria"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VieAlVitoria {
            get {
                return ((int)(this["VieAlVitoria"]));
            }
            set {
                this["VieAlVitoria"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SabDelVitoria {
            get {
                return ((int)(this["SabDelVitoria"]));
            }
            set {
                this["SabDelVitoria"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SabAlVitoria {
            get {
                return ((int)(this["SabAlVitoria"]));
            }
            set {
                this["SabAlVitoria"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DomDelVitoria {
            get {
                return ((int)(this["DomDelVitoria"]));
            }
            set {
                this["DomDelVitoria"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DomAlVitoria {
            get {
                return ((int)(this["DomAlVitoria"]));
            }
            set {
                this["DomAlVitoria"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComodinArrasate {
            get {
                return ((int)(this["ComodinArrasate"]));
            }
            set {
                this["ComodinArrasate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComodinBilbao {
            get {
                return ((int)(this["ComodinBilbao"]));
            }
            set {
                this["ComodinBilbao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComodinDonosti {
            get {
                return ((int)(this["ComodinDonosti"]));
            }
            set {
                this["ComodinDonosti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComodinVitoria {
            get {
                return ((int)(this["ComodinVitoria"]));
            }
            set {
                this["ComodinVitoria"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PagarLimpiezasArrasate {
            get {
                return ((bool)(this["PagarLimpiezasArrasate"]));
            }
            set {
                this["PagarLimpiezasArrasate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PagarLimpiezasBilbao {
            get {
                return ((bool)(this["PagarLimpiezasBilbao"]));
            }
            set {
                this["PagarLimpiezasBilbao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PagarLimpiezasDonosti {
            get {
                return ((bool)(this["PagarLimpiezasDonosti"]));
            }
            set {
                this["PagarLimpiezasDonosti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PagarLimpiezasVitoria {
            get {
                return ((bool)(this["PagarLimpiezasVitoria"]));
            }
            set {
                this["PagarLimpiezasVitoria"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21")]
        public int NumeroLimpiezasArrasate {
            get {
                return ((int)(this["NumeroLimpiezasArrasate"]));
            }
            set {
                this["NumeroLimpiezasArrasate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21")]
        public int NumeroLimpiezasBilbao {
            get {
                return ((int)(this["NumeroLimpiezasBilbao"]));
            }
            set {
                this["NumeroLimpiezasBilbao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21")]
        public int NumeroLimpiezasDonosti {
            get {
                return ((int)(this["NumeroLimpiezasDonosti"]));
            }
            set {
                this["NumeroLimpiezasDonosti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21")]
        public int NumeroLimpiezasVitoria {
            get {
                return ((int)(this["NumeroLimpiezasVitoria"]));
            }
            set {
                this["NumeroLimpiezasVitoria"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal PlusViajeArrasate {
            get {
                return ((decimal)(this["PlusViajeArrasate"]));
            }
            set {
                this["PlusViajeArrasate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal PlusViajeBilbao {
            get {
                return ((decimal)(this["PlusViajeBilbao"]));
            }
            set {
                this["PlusViajeBilbao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal PlusViajeDonosti {
            get {
                return ((decimal)(this["PlusViajeDonosti"]));
            }
            set {
                this["PlusViajeDonosti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal PlusViajeVitoria {
            get {
                return ((decimal)(this["PlusViajeVitoria"]));
            }
            set {
                this["PlusViajeVitoria"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PagarPlusViajeArrasate {
            get {
                return ((bool)(this["PagarPlusViajeArrasate"]));
            }
            set {
                this["PagarPlusViajeArrasate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PagarPlusViajeBilbao {
            get {
                return ((bool)(this["PagarPlusViajeBilbao"]));
            }
            set {
                this["PagarPlusViajeBilbao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PagarPlusViajeDonosti {
            get {
                return ((bool)(this["PagarPlusViajeDonosti"]));
            }
            set {
                this["PagarPlusViajeDonosti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PagarPlusViajeVitoria {
            get {
                return ((bool)(this["PagarPlusViajeVitoria"]));
            }
            set {
                this["PagarPlusViajeVitoria"] = value;
            }
        }
    }
}
