//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orion.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CarpetaDatos {
            get {
                return ((string)(this["CarpetaDatos"]));
            }
            set {
                this["CarpetaDatos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CentroInicial {
            get {
                return ((int)(this["CentroInicial"]));
            }
            set {
                this["CentroInicial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color ColorOV {
            get {
                return ((global::System.Drawing.Color)(this["ColorOV"]));
            }
            set {
                this["ColorOV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Magenta")]
        public global::System.Drawing.Color ColorJD {
            get {
                return ((global::System.Drawing.Color)(this["ColorJD"]));
            }
            set {
                this["ColorJD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Brown")]
        public global::System.Drawing.Color ColorDS {
            get {
                return ((global::System.Drawing.Color)(this["ColorDS"]));
            }
            set {
                this["ColorDS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkViolet")]
        public global::System.Drawing.Color ColorDC {
            get {
                return ((global::System.Drawing.Color)(this["ColorDC"]));
            }
            set {
                this["ColorDC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Chocolate")]
        public global::System.Drawing.Color ColorF6 {
            get {
                return ((global::System.Drawing.Color)(this["ColorF6"]));
            }
            set {
                this["ColorF6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CarpetaAyuda {
            get {
                return ((string)(this["CarpetaAyuda"]));
            }
            set {
                this["CarpetaAyuda"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double TopCalculadora {
            get {
                return ((double)(this["TopCalculadora"]));
            }
            set {
                this["TopCalculadora"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double LeftCalculadora {
            get {
                return ((double)(this["LeftCalculadora"]));
            }
            set {
                this["LeftCalculadora"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BotonCalculadoraActivo {
            get {
                return ((bool)(this["BotonCalculadoraActivo"]));
            }
            set {
                this["BotonCalculadoraActivo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Version {
            get {
                return ((string)(this["Version"]));
            }
            set {
                this["Version"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 192, 192")]
        public global::System.Drawing.Color ColorE {
            get {
                return ((global::System.Drawing.Color)(this["ColorE"]));
            }
            set {
                this["ColorE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CarpetaDropbox {
            get {
                return ((string)(this["CarpetaDropbox"]));
            }
            set {
                this["CarpetaDropbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SincronizarEnDropbox {
            get {
                return ((bool)(this["SincronizarEnDropbox"]));
            }
            set {
                this["SincronizarEnDropbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Informes")]
        public string CarpetaInformes {
            get {
                return ((string)(this["CarpetaInformes"]));
            }
            set {
                this["CarpetaInformes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AbrirPDFs {
            get {
                return ((bool)(this["AbrirPDFs"]));
            }
            set {
                this["AbrirPDFs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CarpetaCopiasSeguridad {
            get {
                return ((string)(this["CarpetaCopiasSeguridad"]));
            }
            set {
                this["CarpetaCopiasSeguridad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CopiaAutomatica {
            get {
                return ((int)(this["CopiaAutomatica"]));
            }
            set {
                this["CopiaAutomatica"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000-01-01")]
        public global::System.DateTime UltimaCopia {
            get {
                return ((global::System.DateTime)(this["UltimaCopia"]));
            }
            set {
                this["UltimaCopia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("n0xvPn6v0UQ=")]
        public string ContraseñaDatos {
            get {
                return ((string)(this["ContraseñaDatos"]));
            }
            set {
                this["ContraseñaDatos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SoloAñoActualEnGruposGraficos {
            get {
                return ((bool)(this["SoloAñoActualEnGruposGraficos"]));
            }
            set {
                this["SoloAñoActualEnGruposGraficos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MostrarGrafNoCalcular {
            get {
                return ((bool)(this["MostrarGrafNoCalcular"]));
            }
            set {
                this["MostrarGrafNoCalcular"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MostrarGrafDescuadres {
            get {
                return ((bool)(this["MostrarGrafDescuadres"]));
            }
            set {
                this["MostrarGrafDescuadres"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MostrarGrafHoras {
            get {
                return ((bool)(this["MostrarGrafHoras"]));
            }
            set {
                this["MostrarGrafHoras"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MostrarGrafDietas {
            get {
                return ((bool)(this["MostrarGrafDietas"]));
            }
            set {
                this["MostrarGrafDietas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MostrarGrafPlusLimpieza {
            get {
                return ((bool)(this["MostrarGrafPlusLimpieza"]));
            }
            set {
                this["MostrarGrafPlusLimpieza"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MostrarGrafPlusPaqueteria {
            get {
                return ((bool)(this["MostrarGrafPlusPaqueteria"]));
            }
            set {
                this["MostrarGrafPlusPaqueteria"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MostrarGrafTiempoPartido {
            get {
                return ((bool)(this["MostrarGrafTiempoPartido"]));
            }
            set {
                this["MostrarGrafTiempoPartido"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ActualizarSettings {
            get {
                return ((bool)(this["ActualizarSettings"]));
            }
            set {
                this["ActualizarSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CarpetaOrigenActualizar {
            get {
                return ((string)(this["CarpetaOrigenActualizar"]));
            }
            set {
                this["CarpetaOrigenActualizar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ActualizarPrograma {
            get {
                return ((bool)(this["ActualizarPrograma"]));
            }
            set {
                this["ActualizarPrograma"] = value;
            }
        }
    }
}
